# Generated by Django 4.1.3 on 2022-11-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='average_monthly_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
