# Generated by Django 4.1.3 on 2022-11-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_document_average_monthly_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
