# Generated by Django 4.1.3 on 2022-11-27 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_datacsv_average_monthly_hours_alter_datacsv_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('satisfaction_level', models.FloatField(blank=True, default=0, null=True)),
                ('last_evaluation', models.FloatField(blank=True, default=0, null=True)),
                ('num_project', models.IntegerField(blank=True, default=0, null=True)),
                ('average_monthly_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('time_spend_comapny', models.IntegerField(blank=True, default=0, null=True)),
                ('work_accident', models.BooleanField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='DataCSV',
        ),
    ]
